# Using Piper general purpose pipeline for Azure

trigger:
  - main
  
schedules:
- cron: "0 0 * * *"
  # cron: "*/5 * * * *"
  displayName: pipeline optimization
  branches:
    include: 
      - main
  always: false # whether to always run the pipeline or only if there have been source code changes since the last successful scheduled run. The default is false.


resources:
  repositories:
  - repository: piper-pipeline-azure
    endpoint: github.tools.sap
    ref: jliempt/confirmTimeout
    type: githubenterprise
    name: project-piper/piper-pipeline-azure

extends:
  template: sap-piper-pipeline.yml@piper-pipeline-azure