# Using Piper general purpose pipeline for Azure

trigger:
  - main

resources:
  repositories:
  - repository: piper-pipeline-azure
    endpoint: github.tools.sap
    ref: D032835-patch-2
    type: githubenterprise
    name: project-piper/piper-pipeline-azure

extends:
  template: sap-piper-pipeline.yml@piper-pipeline-azure
