general:
  buildTool: 'golang'
  productiveBranch: 'main'
  vaultBasePath: 'piper/PIPELINE-GROUP-882'
  vaultPipelineName: 'PIPELINE-9791'
  vaultServerUrl: 'https://vault.tools.sap'
  vaultNamespace: 'ies/hyperspace/pipelines'
  whitesourceProductName: 'SHC - Piper'
  nativeBuild: true
  
  # Jenkins-only
  vaultAppRoleTokenCredentialsId: vault-approle-role-id-882
  vaultAppRoleSecretTokenCredentialsId: vault-approle-secret-id-882
stages:
steps:
  artifactPrepareVersion:
    versioningType: cloud_noTag
  checkmarxExecuteScan:
    projectName: 'azure-demo-k8s-go'
    preset: '100099'
    # serverUrl: 'https://cx.wdf.sap.corp:443'
    teamId: 'b75c657f-55c7-483c-ac76-9589f378fa75'
    vulnerabilityThresholdLow: 0
  sapCallStagingService:
    url: 'https://staging.repositories.cloud.sap/stage/api'
    profile: 'group-882-default'
  sapCumulusUpload:
    pipelineId: '1e3816b1-99a5-4b19-8a0d-0deeb4b924c8'
  whitesourceExecuteScan:
    projectName: 'azure-demo-k8s-go'
  
