general:
  buildTool: 'golang'
  githubApiUrl: 'https://github.tools.sap/api/v3'
  pipelineOptimization: true
  productiveBranch: 'main'
  owner: project-piper
  repository: azure-demo-k8s-go
  vaultBasePath: 'piper/PIPELINE-GROUP-882'
  vaultPipelineName: 'PIPELINE-9791'
  vaultNamespace: 'ies/hyperspace/pipelines'
  whitesourceProductName: 'SHC - Piper'
  nativeBuild: true
  verbose: true
  
  # Jenkins-only
  # vaultAppRoleTokenCredentialsId: vault-approle-role-id-882
  # vaultAppRoleSecretTokenCredentialsId: vault-approle-secret-id-882
stages:
steps:
  artifactPrepareVersion:
    versioningType: cloud_noTag
  checkmarxExecuteScan:
    projectName: 'azure-demo-k8s-go'
    preset: '100099'
    # serverUrl: 'https://cx.wdf.sap.corp:443'
    teamId: 'b75c657f-55c7-483c-ac76-9589f378fa75'
    vulnerabilityThresholdLow: 0
  sapCallStagingService:
    url: 'https://staging.repositories.cloud.sap/stage/api'
    profile: 'group-882-default'
  sapCheckPPMSCompliance:
    #createBuildVersion: true
    #uploadChangeRequest: true
    ppmsID: '73554900100200018611'
  sapCumulusUpload:
    pipelineId: '1e3816b1-99a5-4b19-8a0d-0deeb4b924c8'
  whitesourceExecuteScan:
    buildDescriptorFile: go.mod
  
