general:
  buildTool: 'golang'
  productiveBranch: 'main'
  vaultBasePath: 'piper/PIPELINE-GROUP-882'
  vaultPipelineName: 'PIPELINE-9791'
  vaultServerUrl: 'https://vault.tools.sap'
  vaultNamespace: 'ies/hyperspace/pipelines'
  nativeBuild: true
stages:
steps:
  sapCallStagingService:
    url: 'https://staging.repositories.cloud.sap/stage/api'
    profile: 'group-882-default'
  sapCumulusUpload:
    pipelineId: '1e3816b1-99a5-4b19-8a0d-0deeb4b924c8'
