# Default values for Acceptance stage of azure-demo-k8s-go.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

ingress:
  hosts:
    - host: azure-demo-k8s-go.ingress.jwl5c5xfg1.piper-cd.shoot.canary.k8s-hana.ondemand.com
      paths: 
        - /