{{- if .Values.secret -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: "{{ .Values.secret.name }}"
data:
  .dockerconfigjson: "{{ .Values.secret.dockerconfigjson }}"
{{- end }}