# Default values for Acceptance stage of sample-k8s-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

ingress:
  hosts:
    - host: azure-demo-k8s-go.dev-ext-gcp.toolsteam.shoot.canary.k8s-hana.ondemand.com
      paths: 
        - /